"use strict";
const data = [{
  name: '用工',
  fileId: 'f_1',
  objectType: 6,
  expanded: false,
  folder: true,
  children: [{
    name: '财务',
    fileId: 'c_0',
    type: 5,
    folder: false
  }, {
    name: '人员',
    fileId: 'c_1',
    type: 5,
    folder: false
  }, {
    name: '项目',
    fileId: 'c_2',
    type: 5,
    folder: false
  }, {
    name: '物资',
    fileId: 'c_3',
    type: 5,
    folder: false
  }, {
    name: '资产',
    fileId: 'c_4',
    type: 5,
    folder: false
  }, {
    name: '设备',
    fileId: 'c_5',
    type: 5,
    folder: false
  }, {
    name: '市场',
    fileId: 'c_6',
    type: 5,
    folder: false
  }, {
    name: '电网',
    fileId: 'c_7',
    type: 5,
    folder: false
  }, {
    name: '客户',
    fileId: 'c_8',
    type: 5,
    folder: false
  }, {
    name: '产品',
    fileId: 'c_9',
    type: 5,
    folder: false
  }, {
    name: '综合',
    fileId: 'c_10',
    type: 5,
    folder: false
  }, {
    name: '安全',
    fileId: 'c_11',
    type: 5,
    folder: false
  }]
}, {
  name: '薪酬',
  fileId: 'f_2',
  objectType: 6,
  expanded: false,
  folder: true,
  children: [{
    name: '财务',
    fileId: 'c_12',
    type: 5,
    folder: false
  }, {
    name: '人员',
    fileId: 'c_13',
    type: 5,
    folder: false
  }, {
    name: '项目',
    fileId: 'c_14',
    type: 5,
    folder: false
  }, {
    name: '物资',
    fileId: 'c_15',
    type: 5,
    folder: false
  }, {
    name: '资产',
    fileId: 'c_16',
    type: 5,
    folder: false
  }, {
    name: '设备',
    fileId: 'c_17',
    type: 5,
    folder: false
  }, {
    name: '市场',
    fileId: 'c_18',
    type: 5,
    folder: false
  }, {
    name: '电网',
    fileId: 'c_19',
    type: 5,
    folder: false
  }, {
    name: '客户',
    fileId: 'c_20',
    type: 5,
    folder: false
  }, {
    name: '产品',
    fileId: 'c_21',
    type: 5,
    folder: false
  }, {
    name: '综合',
    fileId: 'c_22',
    type: 5,
    folder: false
  }, {
    name: '安全',
    fileId: 'c_23',
    type: 5,
    folder: false
  }]
}, {
  name: '员工',
  fileId: 'f_3',
  objectType: 6,
  expanded: false,
  folder: true,
  children: [{
    name: '财务',
    fileId: 'c_24',
    type: 5,
    folder: false
  }, {
    name: '人员',
    fileId: 'c_25',
    type: 5,
    folder: false
  }, {
    name: '项目',
    fileId: 'c_26',
    type: 5,
    folder: false
  }, {
    name: '物资',
    fileId: 'c_27',
    type: 5,
    folder: false
  }, {
    name: '资产',
    fileId: 'c_28',
    type: 5,
    folder: false
  }, {
    name: '设备',
    fileId: 'c_29',
    type: 5,
    folder: false
  }, {
    name: '市场',
    fileId: 'c_30',
    type: 5,
    folder: false
  }, {
    name: '电网',
    fileId: 'c_31',
    type: 5,
    folder: false
  }, {
    name: '客户',
    fileId: 'c_32',
    type: 5,
    folder: false
  }, {
    name: '产品',
    fileId: 'c_33',
    type: 5,
    folder: false
  }, {
    name: '综合',
    fileId: 'c_34',
    type: 5,
    folder: false
  }, {
    name: '安全',
    fileId: 'c_35',
    type: 5,
    folder: false
  }]
}, {
  name: '绩效',
  fileId: 'f_4',
  objectType: 6,
  expanded: false,
  folder: true,
  children: [{
    name: '财务',
    fileId: 'c_36',
    type: 5,
    folder: false
  }, {
    name: '人员',
    fileId: 'c_37',
    type: 5,
    folder: false
  }, {
    name: '项目',
    fileId: 'c_38',
    type: 5,
    folder: false
  }, {
    name: '物资',
    fileId: 'c_39',
    type: 5,
    folder: false
  }, {
    name: '资产',
    fileId: 'c_40',
    type: 5,
    folder: false
  }, {
    name: '设备',
    fileId: 'c_41',
    type: 5,
    folder: false
  }, {
    name: '市场',
    fileId: 'c_42',
    type: 5,
    folder: false
  }, {
    name: '电网',
    fileId: 'c_43',
    type: 5,
    folder: false
  }, {
    name: '客户',
    fileId: 'c_44',
    type: 5,
    folder: false
  }, {
    name: '产品',
    fileId: 'c_45',
    type: 5,
    folder: false
  }, {
    name: '综合',
    fileId: 'c_46',
    type: 5,
    folder: false
  }, {
    name: '安全',
    fileId: 'c_47',
    type: 5,
    folder: false
  }]
}, {
  name: '培训',
  fileId: 'f_5',
  objectType: 6,
  expanded: false,
  folder: true,
  children: [{
    name: '财务',
    fileId: 'c_36',
    type: 5,
    folder: false
  }, {
    name: '人员',
    fileId: 'c_37',
    type: 5,
    folder: false
  }, {
    name: '项目',
    fileId: 'c_38',
    type: 5,
    folder: false
  }, {
    name: '物资',
    fileId: 'c_39',
    type: 5,
    folder: false
  }, {
    name: '资产',
    fileId: 'c_40',
    type: 5,
    folder: false
  }, {
    name: '设备',
    fileId: 'c_41',
    type: 5,
    folder: false
  }, {
    name: '市场',
    fileId: 'c_42',
    type: 5,
    folder: false
  }, {
    name: '电网',
    fileId: 'c_43',
    type: 5,
    folder: false
  }, {
    name: '客户',
    fileId: 'c_44',
    type: 5,
    folder: false
  }, {
    name: '产品',
    fileId: 'c_45',
    type: 5,
    folder: false
  }, {
    name: '综合',
    fileId: 'c_46',
    type: 5,
    folder: false
  }, {
    name: '安全',
    fileId: 'c_47',
    type: 5,
    folder: false
  }]
}, {
  name: '组织',
  fileId: 'f_6',
  objectType: 6,
  expanded: false,
  folder: true,
  children: [{
    name: '财务',
    fileId: 'c_48',
    type: 5,
    folder: false
  }, {
    name: '人员',
    fileId: 'c_49',
    type: 5,
    folder: false
  }, {
    name: '项目',
    fileId: 'c_50',
    type: 5,
    folder: false
  }, {
    name: '物资',
    fileId: 'c_51',
    type: 5,
    folder: false
  }, {
    name: '资产',
    fileId: 'c_52',
    type: 5,
    folder: false
  }, {
    name: '设备',
    fileId: 'c_53',
    type: 5,
    folder: false
  }, {
    name: '市场',
    fileId: 'c_54',
    type: 5,
    folder: false
  }, {
    name: '电网',
    fileId: 'c_55',
    type: 5,
    folder: false
  }, {
    name: '客户',
    fileId: 'c_56',
    type: 5,
    folder: false
  }, {
    name: '产品',
    fileId: 'c_57',
    type: 5,
    folder: false
  }, {
    name: '综合',
    fileId: 'c_58',
    type: 5,
    folder: false
  }, {
    name: '安全',
    fileId: 'c_59',
    type: 5,
    folder: false
  }]
}]

export default data;
