"use strict";
//noinspection JSDuplicatedDeclaration
module.exports = {
  ADD_ANNULAR: "addAnnular",
  ADD_FLOW: "addFlow",
  REMOVE_ANNULAR: "removeAnnular",
  REMOVE_NODE: "removeNodes",
  REMOVE_DOMAINDETIAL:"removeDomainDetial",
  EXPLORE_NODE: "exploreNode",
  UNEXPLORE_NODE: "unExploreNode",
  CLOSE_EXPLORENODE: "closeExploreNodes",
  FOCUS_NODE: "focusNode",
  UNFOCUS_NODE: "unFocusNode",
  SHOW_CXTMENU: "showCtxMenu",
  SHOW_DETAILCIRCLE: "showDetailCircle",
  REMOVE_DETAILCIRCLE: "removeDetailCircle",
  ADD_CHILDANNULAR: "addChildAnnular",
  SHOW_DETAILENTITY: "showDetailentity",
  HIDE_DETAILENTITY: "hideDetailentity",
  CLUSTER_SHOW_TIPS: "clusterShowTips",
  CLUSTER_HIDE_TIPS: "clusterHideTips",
  ENTITY_RECOMMENT_MODAL: "entity_recomment_modal",
  GOTO_CANVAS_STATE: "goto_canvas_state",
  TREE_ADD_NODE: "tree_add_node",
  TREE_DELETE_NODE: "tree_delete_node",
  TAGSBAR_DELETE_NODE:"tagsBar_delete_node",
  TAGSBAR_UPDATE_NODE:"tagsBar_update_node",
  ENTER_FOLDER: "enter_folder",
  SHOW_MULTIPILE_DROPDOWN: "show_multipile_dropdown",
  HIDE_MULTIPILE_DROPDOWN: "hide_multipile_dropdown",
  TREE_EDIT_NODE: "tree_edit_node",
  LOCATE_POSITION: "locate_position",
  OPEN_TABLE_PAGE: "open_table_page",
  SHOW_CREATE_CANVAS_MODAL: "show_create_canvas_modal",
  SHOW_CREATE_FLOW_MODAL: "show_create_flow_modal",
  SHOW_CREATE_FOLDER_MODAL: "show_create_folder_modal",
  SHOW_EDIT_FOLDER_MODAL: "show_edit_folder_modal",
  TOPOLOGY_LOCATE_STATUS: "topology_locate_status",
  CHANGE_MAIN_VIEW: "change_main_view",
  SHOW_DELETE_FOLDER_MODAL: "show_delete_folder_modal",
  ADD_ITEM_CONDITION_MODAL: "add_item_condition_modal",
  REMOVE_ITEM_CONDITION_MODAL: "remove_item_condition_modal",
  PATH_CANVAS_DRAWLINK: "path_canvas_drawlink",
  PATH_CANVAS_CONCAT_TREE: "path_canvas_concat_tree",
  PATH_CANVAS_CXTMENUE: "path_canvas_cxtmenu",
  SHOW_EXEC_EXPLORE_MODAL: "show_exec_explore_modal",
  SHOW_EXEC_EXPLORE_INSTS: "show_exec_explore_insts",
  DELETE_EXPLORE_INSTS:"delete_explore_insts",
  SHOW_FOLDER_MENU: "showFolderMenu",
  SHOW_TOP_SUBJECT: "showTopSubject",
  SHOW_SUBJECT: "show_subject",
  SHOW_SUBJECT_NAV: "show_subject_nav",
  APPEND_NAV: "append_nav",
  GO_DEFINE_PAGE: "go_define_page",
  SHOW_CONDITION_TOOLTIPS: "show_condition_tooltips",
  HIDE_CONDITION_TOOLTIPS: "hide_condition_tooltips",
  FOLDER_NODE_CLICK: "folder_node_click",
  DELETE_EXPLORE_MODAL:"delete_explore_modal",
  ADD_INST_TO_TREE: "add_inst_to_tree",
  DEL_INST_TO_TREE: "del_inst_to_tree",
  ADD_DEFINE_TO_TREE: "add_define_to_tree",
  REMOVE_ITEM_INPUTDATA_MODAL:"remove_item_inputdata_modal",
  REMOVE_ITEM_INPUTDATA:"remove_item_inputdata",
  SHOW_DELETE_BTN: "show_delete_btn",
  DELETE_FLOW: "delete_flow",
  SHOW_EXEC_DEFINEINSTS_MODAL:"show_exec_defineInsts_modal",
  TAGSBAR_INIT_NODE:"tagsBar_init_node",
  TAGSBAR_ADD_NODE:"tagsBar_add_node"
};
